//store module
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCT = "GET_PRODUCT";
export const ADD_REVIEW = "ADD_REVIEW";
export const GET_CATEGORY_PRODUCTS = "GET_CATEGORY_PRODUCTS";
export const PRODUCT_ERROR = "PRODUCT_ERROR";

export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_CATEGORY = "GET_CATEGORY";
export const CATEGORY_ERROR= "CATEGORY_ERROR";

export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const ADD_TO_CART = "ADD_TO_CART";
export const GET_ITEMS = "GET_ITEMS";
export const CART_ERROR = "CART_ERROR";
export const REMOVE_ITEM_FROM_CART="REMOVE_ITEM_FROM_CART";

export const SAVE_SHIPPING_DETAILS = "SAVE_SHIPPING_DETAILS";
export const SHIPPING_DETAILS_ERROR= "SHIPPING_DETAILS_ERROR";

export const ADD_ORDER= "ADD_ORDER";
export const ORDER_ERROR= "ORDER_ERROR";

//service Module
export const GET_CURRENT_PROFILE= "GET_CURRENT_PROFILE";
export const CREATE_PROFILE= "CREATE_PROFILE";
export const EDIT_PROFILE= "EDIT_PROFILE";
export const ADD_LOCATION= "ADD_LOCATION";
export const ADD_SERVICES= "ADD_SERVICES";
export const GET_SERVICES= "GET_SERVICES";
export const DELETE_SERVICE= "DELETE_SERVICE";
export const GET_LIMITED_PROFILES= "GET_LIMITED_PROFILES";
export const GET_PROFILES= "GET_PROFILES";

export const GET_SPECIFIC_PROFILE= "GET_SPECIFIC_PROFILE";
export const GET_SPECIFIC_SERVICE= "GET_SPECIFIC_SERVICE";

export const ADD_SERVICE_TO_CART= "ADD_SERVICE_TO_CART";

export const CREATE_APPOINTMENT = "CREATE_APPOINTMENT";
export const GET_APPOINTMENTS = "GET_APPOINTMENTS";
export const GET_APPOINTMENT = "GET_APPOINTMENT";
export const DELETE_APPOINTMENT = "DELETE_APPOINTMENT";

